"""init

Revision ID: 2bfe7d6f4ec9
Revises: 
Create Date: 2026-09-19 15:49:29.531733

"""
import sqlalchemy as sa

from alembic import op

revision = '2bfe7d6f4ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_id'), 'examples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examples_id'), table_name='examples')
    op.drop_table('examples')
    # ### end Alembic commands ###
